Tweak rsync to preserve original files that were getting deleted

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -2,7 +2,14 @@
 
 CYAN='\033[36m'
 GREEN="\033[1;32m"
+RED="\033[0;31m"
 NC='\033[0m' # No Color
+
+if ! command -v rsync &> /dev/null
+then
+  echo -e "${RED}rsync is required for this script, please install via: brew install rsync"
+  exit 1
+fi
 
 echo -e "${GREEN} Beginning CKEditor build... \n$COMMAND${NC}"
 
@@ -14,13 +21,13 @@ done
 
 echo -e "${CYAN} Copying custom plugins to node_modules/ckeditor-dev/plugins... \n$COMMAND${NC}"
 mkdir -p node_modules/ckeditor-dev/plugins
-rsync -ar plugins/ node_modules/ckeditor-dev/plugins/
+rsync -arv plugins/ node_modules/ckeditor-dev/plugins/
 
 echo -e "${CYAN} Copying build config... \n$COMMAND${NC}"
-rsync ckeditor-build-config.js node_modules/ckeditor-dev/dev/builder/build-config.js
+rsync -av ckeditor-build-config.js node_modules/ckeditor-dev/dev/builder/build-config.js
 
 echo -e "${CYAN} Copying custom skin... \n$COMMAND${NC}"
-rsync -ar skins/sombrero node_modules/ckeditor-dev/skins
+rsync -arv skins/sombrero node_modules/ckeditor-dev/skins
 
 echo -e "${CYAN} Granting execute permissions to build script... \n$COMMAND${NC}"
 chmod +x node_modules/ckeditor-dev/dev/builder/build.sh
@@ -33,8 +40,8 @@ rm -rf dist
 mkdir dist
 
 echo -e "${CYAN} Copying build output to dist/ directory... \n$COMMAND${NC}"
-rsync -ar node_modules/ckeditor-dev/dev/builder/release/ckeditor dist/
-rsync contents.css dist/ckeditor/contents.css
-rsync skins/sombrero/skin.js dist/ckeditor/skins/sombrero
+rsync -arv node_modules/ckeditor-dev/dev/builder/release/ckeditor dist/
+rsync -av contents.css dist/ckeditor/contents.css
+rsync -av skins/sombrero/skin.js dist/ckeditor/skins/sombrero
 
 echo -e "${GREEN} Fín $COMMAND${NC}"
